# Generated by Django 5.2.3 on 2025-07-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_productimage_created_at_alter_brand_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='icon',
            field=models.ImageField(upload_to='brand_icons/'),
        ),
    ]
