# Generated by Django 5.2.3 on 2025-07-02 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_brand_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adminapp.productcolor'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='adminapp.productcolor'),
        ),
    ]
