# Generated by Django 5.2.3 on 2025-07-22 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_product_discount_price_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price (same for all sizes)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Original price (same for all sizes)', max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='adminapp.product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productsizestock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productimage',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adminapp.productcolorvariant'),
        ),
        migrations.AddField(
            model_name='productsizestock',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='adminapp.productcolorvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='productsizestock',
            unique_together={('color_variant', 'size')},
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.RemoveField(
            model_name='productsizestock',
            name='product',
        ),
    ]
