# Generated by Django 5.2.3 on 2025-10-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
