# Generated by Django 5.2.3 on 2025-10-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_categoryoffer_is_deleted_productoffer_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='category',
            field=models.ManyToManyField(related_name='offers', to='adminapp.category'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='product',
            field=models.ManyToManyField(related_name='offers', to='adminapp.product'),
        ),
    ]
