# Generated by Django 5.2.3 on 2025-10-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_remove_categoryoffer_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='categories',
            field=models.ManyToManyField(related_name='category_offers', to='adminapp.category'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='products',
            field=models.ManyToManyField(related_name='product_offers', to='adminapp.product'),
        ),
    ]
