# Generated by Django 5.2.3 on 2025-10-24 04:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_categoryoffer_created_at_productoffer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='icon',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='brand_icon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_image'),
        ),
    ]
