# Generated by Django 5.2.3 on 2025-10-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_alter_brand_icon_alter_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='icon',
            field=models.ImageField(upload_to='brand_icons/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
