# Generated by Django 5.2.3 on 2025-10-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_alter_brand_icon_alter_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizestock',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=1),
        ),
    ]
