# Generated by Django 5.2.3 on 2025-07-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_customuser_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='zip_code',
            new_name='pin_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
