# Generated by Django 5.2.3 on 2025-07-26 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_remove_productimage_product_and_more'),
        ('userapp', '0012_cartitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.productcolorvariant'),
        ),
    ]
