# Generated by Django 5.2.3 on 2025-07-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_remove_productimage_product_and_more'),
        ('userapp', '0013_cartitem_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'color', 'size')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
    ]
