# Generated by Django 5.2.3 on 2025-07-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_remove_productimage_product_and_more'),
        ('userapp', '0016_auto_20250731_1741'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'color_variant')},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
    ]
