# Generated by Django 5.2.3 on 2025-08-06 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_remove_productimage_product_and_more'),
        ('userapp', '0018_auto_20250731_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.productcolorvariant'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.productsizestock'),
        ),
    ]
