# Generated by Django 5.2.3 on 2025-08-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_remove_productimage_product_and_more'),
        ('userapp', '0020_populate_cartitem_variants'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='color_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.productcolorvariant'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.productsizestock'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'color_variant', 'size_stock')},
        ),
    ]
