# Generated by Django 5.2.3 on 2025-08-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
    ]
