# Generated by Django 5.2.3 on 2025-08-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_remove_orderitem_size_order_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size_stock',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
