# Generated by Django 5.2.3 on 2025-08-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_order_payment_status_order_returned_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
    ]
