# Generated by Django 5.2.3 on 2025-09-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.CharField(default='TEMP123', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
