# Generated by Django 5.2.3 on 2025-09-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0033_orderitem_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_status',
        ),
    ]
