from django.urls import path
from . import views

urlpatterns = [
    path('', views.user_signup, name='user_signup'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('resend-otp/', views.resend_otp, name='resend_otp'),  
    path('user_home/', views.user_home, name='user_home'),
    path('userproducts/', views.user_product_list, name='userproduct_list'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('profile/', views.profile_view, name='profile'),
    path('upload_profile_image/',views.upload_profile_image,name='upload_profile_image'),
    path('profile/delete-image/', views.delete_profile_image, name='delete_profile_image'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('profile/resend-otp/', views.resend_profile_otp, name='resend_profile_otp'),
    path('addresses/', views.address_list, name='address_list'),
    path('addresses/add/', views.add_address, name='add_address'),
    path('addresses/update/<int:pk>/', views.update_address, name='update_address'),
    path('addresses/delete/<int:pk>/', views.delete_address, name='delete_address'),
    path('cart/',views.cart_view, name='cart_view'),
    path('cart/add/<int:product_id>/',views.add_to_cart, name='add_to_cart'),
    path('get_sizes/<int:color_variant_id>/',views.get_sizes, name='get_sizes'),
    path('cart/update/<int:cart_item_id>/',views.update_cart_quantity, name='update_cart_quantity'),
    path('cart/remove/<int:cart_item_id>/',views.remove_from_cart, name='remove_from_cart'),
    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('wishlist/add/<int:color_variant_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:wishlist_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/add-to-cart/', views.add_to_cart_from_wishlist, name='add_to_cart_from_wishlist'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('apply-coupon/', views.apply_coupon, name='apply_coupon'),
    path('remove-coupon/', views.remove_coupon, name='remove_coupon'),
    path('place-order/', views.place_order, name='place_order'),
    path('payment_handler/',views.payment_handler,name='payment_handler'),
    path('payment-failed/', views.payment_failed, name='payment_failed'),
    path('order-success/<int:order_id>/', views.order_success, name='order_success'),
    path('orders/',views.orders_list_view, name='orders_list'),
    path('orders/invoice/<int:order_id>/',views.download_invoice, name='download_invoice'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
    path('orders/<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),
    path('return-order/<int:order_id>/', views.return_order, name='return_order'),
    path("wallet/", views.wallet_page, name="wallet_page"),
    path("orders/<int:order_id>/refund/", views.process_return_request, name="process_return_request"),
    path("password/", views.change_password, name="change_password"),
    path('referral/', views.referral_view, name='referral'),
    path('apply-referral/', views.apply_referral, name='apply_referral'),
    path('about/', views.about, name='about'),
    path('contact/', views.about, name='contact'),

]
